apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.appName  }}
  name: {{ .Values.appName  }}
spec:
  replicas: {{ .Values.appReplicas  }}
  selector:
    matchLabels:
      app: {{ .Values.appName  }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName  }}
    spec:
      containers:
        - image: "{{ .Values.appImage  }}:{{ .Values.appVersion  }}"
          name: {{ .Values.appName  }}
          ports:
            - containerPort: {{ .Values.containerPort  }}
          env:
          {{- range .Values.containerEnvVar }}
          - name: {{ .name  }}
            value: {{ .value | quote }}
          {{- end }}